---
#ansible-galaxy  install -r requirements.yml
#   requires: ansible-galaxy install geerlingguy.pip
#   requires: ansible-galaxy install geerlingguy.docker

- hosts: dockers
  become: yes
  vars:
    pip_install_packages:
      - name: docker

  roles:
  #requires for aws machines c.f. https://www.liquidweb.com/kb/enable-epel-repository/
  #sudo yum install  wget
  #wget wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  #sudo yum install ./epel-release-latest-7.noarch.rpm 
  #sudo yum install http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.68-1.el7.noarch.rpm
    - geerlingguy.pip
    - geerlingguy.docker

  tasks:
    - name: grafana
      docker_image: 
        name: grafana/grafana

    - name: influxdb
      docker_image: 
        name: influxdb

    - name: telegraf
      docker_image: 
        name: telegraf
