---
- hosts: localhost
  vars:
    vim_dir: "{{ ansible_env.HOME }}/.vim"
    vimrc: "{{ ansible_env.HOME }}/.vimrc"
    settings:
      - file: ~/.bashrc
        lines:
          - alias pbrun='ansible-playbook -i , -v'              # pbrun to run locally the playbook     
          - alias pbcheck='ansible-playbook -i , -v --check'    # pbcheck to check for syntax on this local machine
          - export ANSIBLE_STDOUT_CALLBACK=yaml                 # format output as yaml for readability

      - file: ~/.vimrc
        lines:
          - execute pathogen#infect()
          - set tabstop=4
          - set background=dark
          - colorschema desert
          - set listchars=tab:→\ ,trail:·,precedes:«,extends:»
          - autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab 

  tasks:
          #  - name: Install some required packages
          #    package:
          #      name:
          #       - vim-enhanced
          #       #- fzf
          #      state: installed
          #    become: yes
          #    tags:
          #      - install_packages
          #
  - name: Ensure .vim/{autoload,bundle} directory exists
    file:
      path: "{{ item }}"
      state: directory
      recurse: no
      mode: 0750
    loop:
      - "{{ vim_dir }}"
      - "{{ vim_dir }}/autoload"
      - "{{ vim_dir }}/bundle"

  - name: Ensure Pathogen is in place
    get_url:
      dest: "{{ vim_dir }}/autoload/pathogen.vim"
      url: https://tpo.pe/pathogen.vim

  - name: Deploy plugins # c.f. https://medium.com/@huntie/10-essential-vim-plugins-for-2018-39957190b7a9
    git:
      dest: "{{ vim_dir }}/bundle/{{ item.name }}"
      repo: "{{ item.url }}"
      clone: yes
      update: yes
      recursive: no
    loop:
    - name: indentLine 
      url: https://github.com/Yggdroot/indentLine.git
    - name: nerdtree
      url: https://github.com/preservim/nerdtree
    - name: fzf-vim
      url: https://github.com/junegunn/fzf.vim
    - name: vim-gitgutter
      url: https://github.com/airblade/vim-gitgutter
    - name: lightline 
      url: https://github.com/itchyny/lightline.vim
    - name: vim-multiple-cursors
      url: https://github.com/terryma/vim-multiple-cursors 
    - name: vim-surround
      url: https://github.com/tpope/vim-surround 
    - name: editorconfig-vim
      url: https://github.com/editorconfig/editorconfig-vim
    - name: emmet-vim
      url: https://github.com/mattn/emmet-vim 
    - name: ale
      url: https://github.com/w0rp/ale

  - name: Deploy templated .bashrc_aliases
    copy:
      src: templates/.bash_aliases
      dest: "{{ ansible_env.HOME }}/.bash_aliases"
      backup: yes

  - name: apply some settings (e.g. .bashrc & .vimrc)
    lineinfile: 
      create: yes
      path: "{{ item.0.file }}"
      line: "{{ item.1 }}"  
    with_subelements:
         - "{{ settings }}"
         - lines


